# Generated by Django 2.2.4 on 2019-08-12 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99)),
                ('discount', models.DecimalField(decimal_places=0, help_text='Wpisz zniżkę w %', max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=3)),
                ('multiplier', models.DecimalField(decimal_places=0, max_digits=3)),
                ('formula', models.CharField(help_text='example: int(w)*int(h)+2*(int(d)*int(h))', max_length=200)),
                ('ob_formula', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorscalc.Discount')),
            ],
        ),
    ]
