# Generated by Django 2.1.11 on 2019-08-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='excluded',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
