# Generated by Django 2.1.11 on 2019-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0003_auto_20190813_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='excluded',
            field=models.CharField(max_length=50),
        ),
    ]
