# Generated by Django 2.1.11 on 2019-08-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0004_auto_20190813_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='excluded',
            field=models.CharField(default='', max_length=50),
        ),
    ]
