# Generated by Django 2.1.11 on 2019-08-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0005_auto_20190813_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='excluded',
            field=models.CharField(default='', help_text='wymiar pomijany: width, height, depth', max_length=50),
        ),
    ]
