# Generated by Django 2.1.11 on 2019-08-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0006_auto_20190813_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
