# Generated by Django 2.1.11 on 2019-08-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0007_door_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='preview',
        ),
        migrations.AddField(
            model_name='door',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/static_dirs/images/'),
        ),
    ]
