# Generated by Django 2.1.11 on 2019-08-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0008_auto_20190814_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='image',
            new_name='photo',
        ),
    ]
