# Generated by Django 2.1.11 on 2019-08-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0011_door_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='cover',
            field=models.ImageField(default='image.png', upload_to='images/'),
        ),
    ]
