# Generated by Django 2.1.11 on 2019-08-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0012_auto_20190814_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='excluded',
            field=models.CharField(blank=True, default='', help_text='wymiar pomijany: width, height, depth', max_length=50),
        ),
    ]
