# Generated by Django 2.1.11 on 2019-08-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0013_auto_20190814_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='gasket',
            field=models.BooleanField(default=False),
        ),
    ]
