# Generated by Django 2.1.11 on 2019-08-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0014_door_gasket'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='tooltip',
            field=models.CharField(default='no info', help_text='Wpisz krótki opis pod myszką', max_length=50),
        ),
    ]
