# Generated by Django 2.1.11 on 2019-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0015_door_tooltip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='tooltip',
            field=models.CharField(default='', help_text='Wpisz krótki opis pod myszką', max_length=50),
        ),
    ]
