# Generated by Django 2.2.4 on 2019-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0016_auto_20190816_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='nosna',
            field=models.CharField(choices=[('Cała nośna narożna', 'int(x)*int(y)+int(h)*int(d)'), ('Tylko frontowa nośna', 'int(x)*int(y)')], help_text='Wybierz szybe nośną', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='door',
            name='nosna_max',
            field=models.CharField(blank=True, help_text='Wybierz maksymalną powierzchnie szyby nośnej', max_length=50),
        ),
    ]
