# Generated by Django 2.2.4 on 2019-08-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0017_auto_20190820_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='nosna_max',
            field=models.FloatField(blank=True, help_text='Wybierz maksymalną powierzchnie szyby nośnej', max_length=50),
        ),
    ]
