# Generated by Django 2.2.4 on 2019-08-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0018_auto_20190820_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='nosna_max',
            field=models.FloatField(blank=True, default=0.48, help_text='Wybierz maksymalną powierzchnie szyby nośnej', max_length=50),
        ),
    ]
