# Generated by Django 2.2.4 on 2019-08-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0019_auto_20190820_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='nosna_max',
            field=models.FloatField(default=0.48, help_text='Wybierz maksymalną powierzchnie szyby nośnej', max_length=50),
        ),
    ]
