# Generated by Django 2.2.4 on 2019-08-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0025_auto_20190820_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='nosna',
            field=models.CharField(choices=[('int(w)*int(h)+int(h)*int(d)', 'tylko frontowe w narożnych'), ('int(w)*int(h)', 'całe jako frontowe')], help_text='Wybierz szybe nośną', max_length=50, null=True),
        ),
    ]
