# Generated by Django 2.2.4 on 2019-08-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0028_auto_20190820_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='nosna',
            field=models.CharField(choices=[('int(w)*int(h)+int(h)*int(d)', 'Tylko frontowa w narożnych i trójstronnych'), ('int(w)*int(h)', 'Cała')], help_text='Wybierz szybe nośną', max_length=50, null=True, verbose_name='Skrzydło nośne'),
        ),
        migrations.AlterField(
            model_name='door',
            name='nosna_max',
            field=models.FloatField(default=0.48, help_text='Wybierz maksymalną powierzchnie szyby nośnej', max_length=50, verbose_name='Maks. powierzchnia skrzydła nośnego'),
        ),
    ]
