# Generated by Django 2.2.4 on 2019-08-20 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0029_auto_20190820_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='code',
            field=models.CharField(max_length=3, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='door',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorscalc.Discount', verbose_name='Zniżka'),
        ),
        migrations.AlterField(
            model_name='door',
            name='excluded',
            field=models.CharField(blank=True, default='', help_text='wymiar pomijany: width, height, depth', max_length=50, verbose_name='Wyłączony wymiar'),
        ),
        migrations.AlterField(
            model_name='door',
            name='formula',
            field=models.CharField(help_text='example: int(w)*int(h)+2*(int(d)*int(h))', max_length=200, verbose_name='Pole powierzchni'),
        ),
        migrations.AlterField(
            model_name='door',
            name='gasket',
            field=models.BooleanField(default=False, verbose_name='Uszczelka w zestawie'),
        ),
        migrations.AlterField(
            model_name='door',
            name='multiplier',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Mnożnik'),
        ),
        migrations.AlterField(
            model_name='door',
            name='ob_formula',
            field=models.CharField(max_length=50, verbose_name='Obwód uszczelki'),
        ),
        migrations.AlterField(
            model_name='door',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='door',
            name='tooltip',
            field=models.CharField(default='', help_text='Wpisz krótki opis pod myszką', max_length=50, verbose_name='Podpowiedź'),
        ),
    ]
