# Generated by Django 2.2.4 on 2019-08-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0030_auto_20190820_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='tooltip',
            field=models.CharField(blank=True, default='', help_text='Wpisz krótki opis pod myszką', max_length=50, verbose_name='Podpowiedź'),
        ),
    ]
