# Generated by Django 2.1.11 on 2019-08-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0034_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='door',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='d',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Depth'),
        ),
        migrations.AlterField(
            model_name='order',
            name='h',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='order',
            name='w',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Width'),
        ),
    ]
