# Generated by Django 2.1.11 on 2019-08-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0037_auto_20190822_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Producing', 'Producing')], default='Pending', help_text='Status zamówienia', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
