# Generated by Django 2.2.3 on 2019-08-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0039_order_handle_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='door',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='doorscalc.Door', verbose_name='Type'),
        ),
    ]
