# Generated by Django 2.2.3 on 2019-08-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0040_auto_20190828_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='handle_site',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Top', 'Top'), ('Bottom', 'Bottom')], default=1, help_text='Strona klamki', max_length=50, null=True, verbose_name='Handle'),
        ),
    ]
