# Generated by Django 2.2.3 on 2019-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0041_auto_20190828_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inlet_site',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Top', 'Top'), ('Bottom', 'Bottom')], default=3, help_text='Strona klamki', max_length=50, null=True, verbose_name='Inlet'),
        ),
    ]
