# Generated by Django 2.2.3 on 2019-08-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0042_order_inlet_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='handle_site',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Top', 'Top'), ('Bottom', 'Bottom')], default=1, help_text='Which site takes handle?', max_length=50, null=True, verbose_name='Handle'),
        ),
        migrations.AlterField(
            model_name='order',
            name='inlet_site',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Top', 'Top'), ('Bottom', 'Bottom')], default=2, help_text='Which site takes air-inlet?', max_length=50, null=True, verbose_name='Inlet'),
        ),
    ]
