# Generated by Django 2.2.3 on 2019-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0043_auto_20190828_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inlet_site',
            field=models.CharField(choices=[('Right', 'Right'), ('Left', 'Left'), ('Top', 'Top'), ('Bottom', 'Bottom')], default='Top', help_text='Which site takes air-inlet?', max_length=50, null=True, verbose_name='Inlet'),
        ),
    ]
