# Generated by Django 2.1.11 on 2019-08-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0044_auto_20190828_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='published_date',
        ),
    ]
