# Generated by Django 2.1.11 on 2019-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0045_remove_order_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.CharField(default='', help_text='Your customer name', max_length=100, null=True, verbose_name='Customer'),
        ),
    ]
