# Generated by Django 2.2.3 on 2019-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0046_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
