# Generated by Django 2.2.3 on 2019-08-30 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0047_order_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
