# Generated by Django 2.2.3 on 2019-08-30 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0048_auto_20190830_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Data dodania'),
        ),
    ]
