# Generated by Django 2.2.3 on 2019-08-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0049_auto_20190830_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='days',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Dni'),
        ),
    ]
