# Generated by Django 2.2.4 on 2019-09-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0051_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='days',
        ),
    ]
