# Generated by Django 2.2.4 on 2019-09-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0052_remove_order_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Price [€]'),
        ),
    ]
