# Generated by Django 2.1.11 on 2019-09-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0054_auto_20190901_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='inlet_site',
            field=models.CharField(blank=True, choices=[('Top', 'Top'), ('Bottom', 'Bottom')], default='Top', help_text='Which site takes air-inlet?', max_length=50, null=True, verbose_name='Inlet'),
        ),
    ]
