# Generated by Django 2.1.11 on 2019-09-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorscalc', '0055_auto_20190906_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='cover',
        ),
    ]
